<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Roosterious Dashboard</h1>
    </div>
</div><!-- /.row -->

<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3"></div>

                    <div class="col-xs-9 text-right">
                        <div class="huge" id="dashboard_number_of_lecturers">
                            #
                        </div>

                        <div>
                            Docenten in het systeem
                        </div>
                    </div>
                </div>
            </div><a href="#"></a>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3"></div>

                    <div class="col-xs-9 text-right">
                        <div class="huge" id="dashboard_number_of_classes">
                            #
                        </div>

                        <div>
                            Klasseroosters in het systeem
                        </div>
                    </div>
                </div>
            </div><a href="#"></a>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3"></div>

                    <div class="col-xs-9 text-right">
                        <div class="huge" id="dashboard_number_of_rooms">
                            #
                        </div>

                        <div>
                            Lokalen in het systeem
                        </div>
                    </div>
                </div>
            </div><a href="#"></a>
        </div>
    </div>

    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3"></div>

                    <div class="col-xs-9 text-right">
                        <div class="huge" id="dashboard_number_of_lessons">
                            #
                        </div>

                        <div>
                            gebeurtenissen in het rooster
                        </div>
                    </div>
                </div>
            </div><a href="#"></a>
        </div>
    </div>
</div>

<div class="row" id="update_warning" style="display: none;">
    <div class="col-lg-12">
      <div class="alert alert-danger">
        <strong>Let op: </strong>Op dit moment is Roosterious zijn informatie aan het updaten. Hierdoor kan de informatie onvolledig zijn!
      </div>    
    </div>
</div>

<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Informatie
            </div>

            <div class="panel-body">
              <p>Roosterious biedt roosterinfo aan via een API en een website. Door slim gebruik te maken van de rooster gegevens is er meer informatie op te vragen dan via
              de reguliere roostersite.</p>
              <p>Deze tool is gemaakt door Ruud Greven en is Open Source en beschikbaar op <a href="https://github.com/ruudgreven/roosterious" target="_blank">GitHub</a> voor ontwikkelaars.</p>
              <img src="img/logo.png"/>
              <div class="alert alert-warning">
                Roosterious biedt geen garantie op de juistheid van de data in de roosters. Bovendien kunnen er geen rechten ontleend worden aan de informatie.
              </div>
              <div class="alert alert-danger">
                <strong>Let op: </strong>De site toont alleen dingen in die roosters staan. Ga er dus niet vanuit dat de informatie volledig is (Er zijn ook zaken die niet in de roosters staan, maar bijvoorbeeld wel in een lokaal plaatsvinden).
              </div>
            </div><!-- /.panel-body -->
        </div>
    </div>

    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Versie historie
            </div><!-- /.panel-heading -->

            <div class="panel-body">
                <div class="table-responsive">
                  <table class="table table-striped table-bordered table-hover">
                      <thead>
                          <tr>
                              <th>Versie</th>
                              <th>Aanpassingen</th>
                          </tr>
                          <tr>
	                          <td>v0.4</td>
	                          <td>
		                          <ul>
			                          <li>Datum en tijd optie toegevoegd</li>
			                          <li>Nu volledige JSON, iCal en CSV export mogelijkheden. Yay!</li>
			                          <li>Mooi lijstje met aanpassingen op de site</li>
		                          </ul>
	                          </td>
                          </tr>
                          <tr>
	                          <td>v0.3</td>
	                          <td>
		                          <ul>
			                          <li>Uberkekke, nieuwe layout!</li>
			                          <li>Hippe dashboard site met statistieken</li>
			                          <li>Activiteit roosters toegevoegd</li>
		                          </ul>
	                          </td>
                          </tr>
                          <tr>
	                          <td>v0.2</td>
	                          <td>
		                          <ul>
			                          <li>Fouten gefixt</li>
			                          <li>Conceptroosters toegevoegd</li>
		                          </ul>
	                          </td>
                          </tr>
						  <tr>
	                          <td>v0.1</td>
	                          <td>
		                          <ul>
			                          <li>Initiele versie</li>
		                          </ul>
	                          </td>
                          </tr>
                      </thead>
                  </table>
                </div>
            </div><!-- /.panel-body -->
        </div>
    </div>
  </div><!-- /.row -->
  
  <div class="row">
      <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Updates
            </div><!-- /.panel-heading -->

            <div class="panel-body">
                <p>De roostergegevens zijn op de volgende momenten opgehaald.</p>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered table-hover" id="dataTable-updates">
                      <thead>
                          <tr>
                              <th>Datum</th>
                              <th>Begintijd</th>
                              <th>Eindtijd</th>
                              <th>Aantal lessen</th>
                          </tr>
                      </thead>
                  </table>
                </div>
            </div><!-- /.panel-body -->
        </div>
    </div>
  </div><!-- /.row -->
        
<script type="text/javascript">
$(function() {
  $.getJSON( "api/stats/dashboard.json" , function( data ) {
    $.each(data.response, function(index, statsObj){
      $("#dashboard_number_of_lecturers").html("" + statsObj.number_of_lecturers);
      $("#dashboard_number_of_classes").html("" + statsObj.number_of_classes);
      $("#dashboard_number_of_rooms").html("" + statsObj.number_of_rooms);
      $("#dashboard_number_of_lessons").html("" + statsObj.number_of_lessons);
    });
  });

  $('#dataTable-updates').dataTable({
    "paging":   true,
    "ordering": false,
    "searching": false,
    "lengthChange": false,
    "ajax": {
      "url": "api/stats/updates.json",
      "dataSrc": "response"
    },
    "columns": [
      { "data": "date" },
      { "data": "starttime" },
      { "data": "endtime" },
      { "data": "number_of_lessons" }
    ]
  });
  
  //Check if system is updating
  $.getJSON( "api/stats/is_updating.json" , function( data ) {
    if (data.response == "true") {
      $("#update_warning").show();
    }
  });    
});
</script>
