<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>

<div class="row">
    <div class="col-lg-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          Toon rooster van docent
        </div>
        <div class="panel-body">
          <input type="hidden" id="searchfield" style="width:100%"/>
        </div>
      </div>
    </div>
</div><!-- /.row -->

<div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          Lesrooster van <span id="lecturer_nameplaceholder"><strong>niemand!</strong>, kies iemand hierboven</span>
        </div>
        <div class="panel-body" id="lecturer_scheduleplaceholder">

        </div>
      </div>
    </div>
</div><!-- /.row -->
     
<script type="text/javascript">
  $(function() {
     $("#searchfield").select2({
       placeholder: "Klik om een docent te zoeken",
       minimumInputLength: 1,
       ajax: {
          url: "api/lecturer.json",
          dataType: 'json',
          quietMillis: 100,
          data: function (term, page) { // page is the one-based page number tracked by Select2
              return {
                  q: term, //search term
                  page_limit: 10, // page size
              };
          },
          results: function (data, page) {
            var newData = [];
            $.each(data.response, function (index, item) {
                newData.push({
                    id: item.lecturer_id
                  , text: item.lecturer_name + " (" + item.lecturer_id + ")"
                });
            });
            return { results: newData };
          },
        }
    });
    
    $("#searchfield").on("select2-selecting", function(e) {
      loadScheduleLecturer(e.choice.id, e.choice.text);
    });
    
    
    //Load the schedule of the given lecturer
    function loadScheduleLecturer(id, name) {
      $("#lecturer_nameplaceholder").html("<strong>" + name + "</strong>");
      
      //Load schedule and parse to table 
      loadSchedule("api/schedule/lecturer/" + id + ".json", $("#lecturer_scheduleplaceholder"));
    }
  });
</script>
